export const ACTION_TYPE = {
    SET_USER: 'SET_USER',
    LOGOUT: 'LOGOUT',
    UPDATE_COUNTER: 'UPDATE_COUNTER',
    RESET_PRODUCT_DATA: 'RESET_PRODUCT_DATA',
    UPDATE_PRODUCTS_IN_CART: 'UPDATE_PRODUCTS_IN_CART',
    UPDATE_QUANTITY_PRODUCT: 'UPDATE_QUANTITY_PRODUCT',
    DELETE_PRODUCTS_IN_CART: 'DELETE_PRODUCTS_IN_CART',
    RESET_PRODUCTS_IN_CART: 'RESET_PRODUCTS_IN_CART',
};
