export const ACTION_TYPE = {
    SET_USER: 'SET_USER',
    LOGOUT: 'LOGOUT',
    UPDATE_COUNTER: 'UPDATE_COUNTER',

    SET_PRODUCT: 'SET_PRODUCT',
    SET_LOADER_PRODUCT: 'SET_LOADER_PRODUCT',
    SET_ERROR_MESSAGE_PRODUCT: 'SET_ERROR_MESSAGE_PRODUCT',

    SET_PRODUCTS: 'SET_PRODUCTS',
    UPDATE_PRODUCT: 'UPDATE_PRODUCT',
    ADD_PRODUCT: 'ADD_PRODUCT',
    REMOVE_PRODUCT: 'REMOVE_PRODUCT',
    SET_LOADER_PRODUCTS: 'SET_LOADER_PRODUCTS',
    SORT_OR_FILTER_PRODUCTS: 'SORT_OR_FILTER_PRODUCTS',
    SET_ERROR_MESSAGE_PRODUCTS: 'SET_ERROR_MESSAGE_PRODUCTS',

    SET_CATEGORIES: 'SET_CATEGORIES',
    UPDATE_CATEGORY: 'UPDATE_CATEGORY',
    ADD_CATEGORY: 'ADD_CATEGORY',
    REMOVE_CATEGORY: 'REMOVE_CATEGORY',
    SET_LOADER_CATEGORIES: 'SET_LOADER_CATEGORIES',
    SET_ERROR_MESSAGE_CATEGORIES: 'SET_ERROR_MESSAGE_CATEGORIES',

    SET_PRODUCTS_IN_CART: 'SET_PRODUCTS_IN_CART',
    UPDATE_PRODUCTS_IN_CART: 'UPDATE_PRODUCTS_IN_CART',
    UPDATE_QUANTITY_PRODUCT: 'UPDATE_QUANTITY_PRODUCT',
    DELETE_PRODUCTS_IN_CART: 'DELETE_PRODUCTS_IN_CART',
    RESET_PRODUCTS_IN_CART: 'RESET_PRODUCTS_IN_CART',

    SET_ORDER_DATA: 'SET_ORDER_DATA',
    SET_ORDERS_DATA: 'SET_ORDERS_DATA',
    SET_LOADER_OREDRS: 'SET_LOADER_OREDRS',
    SET_ERROR_MESSAGE_OREDRS: 'SET_ERROR_MESSAGE_OREDRS',
};
