export const ACTION_TYPE = {
    SET_USER: 'SET_USER',
    LOGOUT: 'LOGOUT',
    OPEN_MODAL: 'OPEN_MODAL',
    CLOSE_MODAL: 'CLOSE_MODAL',

    SET_PRODUCTS_DATA: 'SET_PRODUCTS_DATA',
    ADD_PRODUCT: 'ADD_PRODUCT',
    UPDATE_PRODUCT: 'UPDATE_PRODUCT',
    DELETE_PRODUCT: 'DELETE_PRODUCT',
    RESET_PRODUCTS_DATA: 'RESET_PRODUCTS_DATA',

    SET_CATEGORIES_DATA: 'SET_CATEGORIES_DATA',
    ADD_CATEGORY: 'ADD_CATEGORY',
    UPDATE_CATEGORY: 'UPDATE_CATEGORY',
    DELETE_CATEGORY: 'DELETE_CATEGORY',
    RESET_CATEGORIES_DATA: 'RESET_CATEGORIES_DATA',

    SET_COUNTER: 'SET_COUNTER',
    UPDATE_COUNTER: 'UPDATE_COUNTER',
    RESET_COUNTER: 'RESET_COUNTER',

    SET_PRODUCTS_IN_CART: 'SET_PRODUCTS_IN_CART',
    UPDATE_PRODUCTS_IN_CART: 'UPDATE_PRODUCTS_IN_CART',
    UPDATE_QUANTITY_PRODUCT: 'UPDATE_QUANTITY_PRODUCT',
    DELETE_PRODUCTS_IN_CART: 'DELETE_PRODUCTS_IN_CART',
    RESET_PRODUCTS_IN_CART: 'RESET_PRODUCTS_IN_CART',
};
